name: CI/CD for HTML with Docker

on:
  push:
    branches:
      - master  # Chạy pipeline khi push code lên nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t myhtmlapp:latest .

      - name: Tag Docker image
        run: docker tag myhtmlapp:latest mydockerhubusername/myhtmlapp:latest

      - name: Push Docker image to Docker Hub
        run: docker push mydockerhubusername/myhtmlapp:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull mydockerhubusername/myhtmlapp:latest
            docker stop myhtmlapp || true
            docker rm myhtmlapp || true
            docker run -d -p 80:80 --name myhtmlapp mydockerhubusername/myhtmlapp:latest
